### ISSUE TITLE
R^+_* manifold with softplus parametrisation (or other metric)

### ISSUE THREAD

**Issue by emilemathieu** [geoopt/geoopt#111]
Hi all,

Very often diagonal covariance matrices are parametrised through a softplus map to enforce positivity and numerical stability. It would enhance code readability to simply declare the standard deviation to belong to this manifold.

I was wondering whether there was plan to implement such a manifold, or more generally the positive definite manifold.

**Comment by ferrine** [comment]
Hi!
There were no plans to implement such a manifold. And in any case, I think it is important to choose a proper metric for such a case. Why softplus, not log for example? Also important to compare how does it perform against regular log std parametrization. At this point, I have more concerns about it, rather than confidence that one handpick of metric would work well.

**Comment by emilemathieu** [comment]
I guess I should close this then.
