### ISSUE TITLE
How to implement a new manifold?

### ISSUE THREAD

**Issue by sakuraiiiii** [geoopt/geoopt#141]
Hi, I want to implement a manifold composed by all the n-dim unitary matrices, just like Efficient Unitary Neural Network. I think I should implement a subclass of ```Manifold```. I want to know which methods should I implement? Thank you.

**Comment by RikVoorhaar** [comment]
I'm not sure complex numbers are properly supported, at least none of the current methods seem to use them. If you just need real unitary matrices, then you should just use Stiefel manifolds.

Otherwise to answer your question, the meta class `geoopt.manifolds.base.Manifold` describes all the methods expected

**Comment by sakuraiiiii** [comment]
Thank you for yor response. What I need is complex unitary matrices, which correspond to complex Stiefel manifolds. I will read the class ```Manifold```.
